name: cicd-skeleton

on:
  workflow_dispatch:
    # enable for specific paths to run the pipeline
    #paths:
    #  - "**.html"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checks out the code
        run: echo "cloning the code"

  build:
    needs: [checkout]
    runs-on: ubuntu-latest
    steps:
      - name: build the code
        run: echo "building the code"

  test:
    needs: [build]
    runs-on: ubuntu-latest  
    steps:
      - name: test the code
        run: echo "testing the code"

  deploy:
    needs: [test,build]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the code
        run: echo "deploying the code"
