# the workflow name 
name: hello-workflow

on:
  workflow_dispatch: 
# jobs inside the workflow 
jobs:
  # This is the name of the job
  hello:
    # the runner where the job runs
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello everyone"

      - name: print username
        run: echo " hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: show the java version
        run: java --version

      - name: show the docker version
        run: docker --version
